"""Locations used by the reproduction scripts (all relative to the repository; override with env vars).

data/rerun/items.jsonl            items of the version-pinned re-run (same questions/answers/evidence as the
                                  released annotations; sham regions from the re-run's draw)
data/robustness_conditions/<cond>/        robustness conditions (items.jsonl; images regenerated by build_robustness_conditions.py)
outputs/rerun/predictions/        re-run predictions        (unpack_results.py expands results/predictions/*.gz)
outputs/robustness/<cond>/predictions/    robustness-condition predictions
outputs/molmo_fix/predictions/    Molmo-7B-D predictions with model-specific answer extraction (molmo_extract.py)
results/                          shipped JSON results; results/tables and results/figures are regenerated here
"""
import os, sys
from pathlib import Path
REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path: sys.path.insert(0, str(REPO))
E = lambda k, d: Path(os.environ.get(k, d))
RERUN_DATA = E("MEI_RERUN_DATA", REPO / "data" / "rerun")
ROBUSTNESS_DATA = E("MEI_ROBUSTNESS_DATA", REPO / "data" / "robustness_conditions")
RERUN_PRED = E("MEI_RERUN_PRED", REPO / "outputs" / "rerun" / "predictions")
ROBUSTNESS_OUT = E("MEI_ROBUSTNESS_OUT", REPO / "outputs" / "robustness")
MOLMO_FIX = E("MEI_MOLMO_FIX", REPO / "outputs" / "molmo_fix" / "predictions")
COCO_ANN = E("MEI_COCO_ANN", REPO / "data" / "coco" / "annotations" / "instances_val2017.json")
RESULTS = REPO / "results"; TABLES = RESULTS / "tables"; FIGURES = RESULTS / "figures"
ORIGINAL_SUMMARY = RESULTS / "original_run_summary.json"          # values of the main table from the original run
REPRODUCTION = RESULTS / "rerun_reproduction_9models.json"      # re-run vs original run, in item counts
for d in (TABLES, FIGURES): d.mkdir(parents=True, exist_ok=True)
